### PR TITLE
custom skeleton added for coveo

### LINKED ISSUE #648: [SEO] Core Web Vitals - Implement placeholder for the Coveo component block
Could we implement a placeholder height for the Coveo Category component block to reduce CLS

https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-mass-spectrometers-mass-spectrometry-software-html/qwjy80k6fo?form_factor=mobile

image

### PR DESCRIPTION
**Pull request by amlan18041996**
Fix #648 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/cell-counters-analyzers/cell-viability-analyzers
- After: https://648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites.hlx.page/us/en/products/cell-counters-analyzers/cell-viability-analyzers
- After: https://648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites.hlx.page/us/en/products/cellular-imaging-systems/high-content-imaging-systems
- After: https://648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites.hlx.page/us/en/products/cellular-imaging-systems/automated-cell-imaging-systems

### CODE REVIEW

**Comment by davenichols-DHLS** [comment]
@amlan18041996 , @mhaack  and @rgravitvl .  I have been reviewing:

https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cellular-imaging-systems-automated-cell-imaging-systems-html/0y2lx7tx4o?form_factor=mobile

https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-page-us-en-products-cellular-imaging-systems-automated-cell-imaging-systems/2vml0ws8kf?form_factor=mobile

It seems that the pages are optimised from ~50 to ~80 with this change.  Looks good to me, but grateful for your thoughts.

**Comment by davenichols-DHLS** [comment]
Please note that on the new, the server is not cached, so I would also add another ~3 points onto this when in prod.

**Test 1**
•	Current 49:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cellular-imaging-systems-high-content-imaging-systems-html/wuv0exxe3b?form_factor=mobile
•	New 82:  https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-page-us-en-products-cellular-imaging-systems-high-content-imaging-systems/wwj8325o17?form_factor=mobile

**Test 2**
•	Current 50:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cellular-imaging-systems-automated-cell-imaging-systems-html/0y2lx7tx4o?form_factor=mobile
•	New 83:  https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-page-us-en-products-cellular-imaging-systems-automated-cell-imaging-systems/2vml0ws8kf?form_factor=mobile

**Test 3**
•	Current 45:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cell-counters-analyzers-cell-viability-analyzers-html/age3rg1l0e?form_factor=mobile
•	New 70:  https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-page-us-en-products-cell-counters-analyzers-cell-viability-analyzers/tjv3banqdi?form_factor=mobile

**Comment by davenichols-DHLS** [comment]
As discussed with @mhaack , @amlan18041996  - can you see if we can delay the Coveo Atomic library JS files before the 5 second time out

**Review by rgravitvl — APPROVED** [review]

**Comment by davenichols-DHLS** [comment]
New Tests on Friday 16th of Feb:

**Test 1**
•	Current 49:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cellular-imaging-systems-high-content-imaging-systems-html/wuv0exxe3b?form_factor=mobile
•	New 100:  https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-live-us-en-products-cellular-imaging-systems-high-content-imaging-systems/eq0l1nkmiy?form_factor=mobile 
 
**Test 2**
•	Current 50:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cellular-imaging-systems-automated-cell-imaging-systems-html/0y2lx7tx4o?form_factor=mobile
•	New 99:  https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-live-us-en-products-cellular-imaging-systems-automated-cell-imaging-systems/y0xglasvup?form_factor=mobile 
 
**Test 3**
•	Current 45:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-cell-counters-analyzers-cell-viability-analyzers-html/age3rg1l0e?form_factor=mobile
•	New 99: https://pagespeed.web.dev/analysis/https-648-exoskeleton-for-coveo-block--danaher-ls-aem--hlxsites-hlx-live-us-en-products-cell-counters-analyzers-cell-viability-analyzers/q0rx1ntcqt?form_factor=mobile

**Review by davenichols-DHLS — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
