### PR TITLE
951 Accordion animation

### LINKED ISSUE #951: [ReBrand] Add animation to the Accordion
Objective: Add fade-in & fade-out animation for accordion block.

LINK: http://localhost:3000/us/en/solutions/mabs/cell-line-development

Reference: https://codepen.io/cruip/full/OJrgMoe

### PR DESCRIPTION
**Pull request by amlan18041996**
Fix #951 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/confocal-microscopes
- After: https://951-animation-to-accordion--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/confocal-microscopes

### CODE REVIEW

**Comment by rgravitvl** [comment]
Hi @amlan18041996 ,

Still there some issue with smoothness on collapse/Expand of accordion on the given page above. Please check. Thanks.

**Review by rgravitvl — CHANGES_REQUESTED** [review]
Already commented

**Review by sharanagoudapatil — CHANGES_REQUESTED** [review]
@amlan18041996 - Text is getting overlapped with '+' and '-' symbols. Please check
image

**Review by davenichols-DHLS — APPROVED** [review]
I love this, @rgravitvl and @sharanagoudapatil  - can you please review.

**Review by rgravitvl — DISMISSED** [review]
Icon need to referred from icon folder

**Review by davenichols-DHLS — APPROVED** [review]
Approved UX wise, merging now.

**Pull request merged**
