### PR TITLE
button styling on product-category page updated to purple

### LINKED ISSUE #397: [Product Category] Button on Topic page - can it use the purple styling like the blogs

### PR DESCRIPTION
**Pull request by amlan18041996**
Fix #397

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://397-product-category-purple-button--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/how-are-assay-kits-installed

### CODE REVIEW

**Review by davenichols-DHLS — APPROVED** [review]
Perfect, thank you Amlan.  Please merge.

**Comment by davenichols-DHLS** [comment]
@mhaack  - is it worrying the amount of CSS removed from the sytles file?

**Review by davenichols-DHLS — CHANGES_REQUESTED** [review]
Hi @amlan18041996  - this is excellent, but sorry you changed the CTA button text colour - it should be purple like it was and not black.  If you can please change this back then we can merge

**Review by davenichols-DHLS — APPROVED** [review]
Approved, looks great thank you.

**Review by mhaack — APPROVED** [review]

**Pull request merged**
