### PR TITLE
CSS split by block - social-media

### LINKED ISSUE #754: CSS split by block - social-media

### PR DESCRIPTION
**Pull request by sharanagoudapatil**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #754 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://754-css-split-social-media--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/overcoming-gene-therapy-viral-vector-production-challenges

### CODE REVIEW

**Review by davenichols-DHLS — CHANGES_REQUESTED** [review]
Hi Sharan,

Looks great, but sorry, the icons are missing on the block.  Please can you add this back in and then it's good from me.

image

**Comment by sharanagoudapatil** [comment]
@davenichols-DHLS - It is fixed now. Please check. Thanks.

**Review by davenichols-DHLS — APPROVED** [review]
Looking great to me now, thank you.

**Review by mhaack — APPROVED** [review]
This shrink the styles.css by > 200 lines, nice.

**Pull request merged**
